version: '3'
services:
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:6.8.6
        environment:
            - discovery.type=single-node
        network_mode: bridge
        ports:
            - 9200:9200
            - 9300:9300
