version: "3"
services:
  redis-master-1:
    container_name: redis-master-7001
    image: redis:6.0.5
    ports:
      - 7001:7001
    volumes:
      - ./config/redis-1.conf:/etc/redis/redis.conf
      - ./logs/redis-1:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"
  redis-master-2:
    container_name: redis-master-7002
    image: redis:6.0.5
    ports:
      - 7002:7002
    volumes:
      - ./config/redis-2.conf:/etc/redis/redis.conf
      - ./logs/redis-2:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"
  redis-master-3:
    container_name: redis-master-7003
    image: redis:6.0.5
    ports:
      - 7003:7003
    volumes:
      - ./config/redis-3.conf:/etc/redis/redis.conf
      - ./logs/redis-3:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"

  redis-slave-4:
    container_name: redis-slave-7004
    image: redis:6.0.5
    ports:
      - 7004:7004
    volumes:
      - ./config/redis-4.conf:/etc/redis/redis.conf
      - ./logs/redis-4:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"
  redis-slave-5:
    container_name: redis-slave-7005
    image: redis:6.0.5
    ports:
      - 7005:7005
    volumes:
      - ./config/redis-5.conf:/etc/redis/redis.conf
      - ./logs/redis-5:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"
  redis-slave-6:
    container_name: redis-slave-7006
    image: redis:6.0.5
    ports:
      - 7006:7006
    volumes:
      - ./config/redis-6.conf:/etc/redis/redis.conf
      - ./logs/redis-6:/logs/redis
    command: redis-server /etc/redis/redis.conf
    network_mode: "host"
    
    
