version: "3.7"
services:
    portainer:
        restart: always
        container_name: portainer
        image: portainer/portainer:1.24.1
        network_mode: bridge
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
volumes:
    portainer_data: {}
