version: '3'

services:
  mysql-db:
    container_name: mysql
    image: mysql
    # network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql_data:/var/lib/mysql"       # 挂载数据目录
      - "./config:/etc/mysql/conf.d"      # 挂载配置文件目录
volumes:
    mysql_data: {}
