version: '3'
  services:
    master:
      image: redis
      container_name: redis-master
      ports:
        - 6379:6379
      volumes:
        - ./redis-master.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
    slave1:
      image: redis
      container_name: redis-slave-1
      ports:
        - 6380:6379
      volumes:
        - ./redis-slave-1.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
    slave2:
      image: redis
      container_name: redis-slave-2
      ports:
        - 6381:6379
      volumes:
        - ./redis-slave-2.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
